apiVersion: v1
kind: Service
metadata:
  name: retail-frontend
spec:
  type: NodePort
  selector:
    app: retail-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-frontend
  template:
    metadata:
      labels:
        app: retail-frontend
    spec:
      containers:
        - name: frontend
          image: avantika1120/retail-order-inventory-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
